-- MySQL Script generated by MySQL Workbench
-- Tue Nov 14 19:31:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `id` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(255) NULL,
  `genero` CHAR(1) NOT NULL,
  `estcivil` CHAR(1) NOT NULL,
  `fone` VARCHAR(12) NOT NULL,
  `fone2` VARCHAR(12) NULL,
  `renda` VARCHAR(15) NOT NULL,
  `escolaridade` VARCHAR(30) NOT NULL,
  `deficiencia_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id` INT NOT NULL,
  `logradouro` VARCHAR(255) NOT NULL,
  `numero` INT(7) NOT NULL,
  `bairro` VARCHAR(45),
  `cidade` VARCHAR(25) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `complemento` VARCHAR(200) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_pessoa_idx` (`pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_pessoa`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`deficiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deficiencia` (
  `id` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `cid` VARCHAR(5) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`pessoadeficiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoadeficiencia` (
  `id` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `pessoa_id` INT NOT NULL,
  `deficiencia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoadeficiencia_pessoa1_idx` (`pessoa_id` ASC) VISIBLE,
  INDEX `fk_pessoadeficiencia_deficiencia1_idx` (`deficiencia_id` ASC) VISIBLE,
  CONSTRAINT `fk_pessoadeficiencia_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoadeficiencia_deficiencia1`
    FOREIGN KEY (`deficiencia_id`)
    REFERENCES `mydb`.`deficiencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
