# Generated by Django 5.0.3 on 2024-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_image_description_alter_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='short_description',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
