# Generated by Django 5.0.3 on 2024-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default='Descrição', max_length=250),
        ),
        migrations.AlterField(
            model_name='image',
            name='short_description',
            field=models.TextField(default='Descrição curta', max_length=40),
        ),
    ]
