# Generated by Django 5.0.3 on 2024-03-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_image_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_full',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
