# Generated by Django 5.0.3 on 2024-03-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_image_image_full'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_thumbnail',
        ),
    ]
