# Generated by Django 5.0.3 on 2024-04-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_image_image_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default='Descrição', max_length=1000),
        ),
    ]
